package com.google.android.gms.common.api.internal;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

public class zzt<R extends Result> extends PendingResult<R> {
   private final Status zzUX;

   @NonNull
   Status getStatus() {
      return this.zzUX;
   }

   public void setResultCallback(@NonNull ResultCallback<? super R> var1) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   public void setResultCallback(@NonNull ResultCallback<? super R> var1, long var2, @NonNull TimeUnit var4) {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }

   @Nullable
   public Integer zzpa() {
      throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
   }
}
