package com.google.analytics.containertag.common;

public enum FunctionType {
    ADROLL_SMART_PIXEL("_asp"),
    ADVERTISER_ID("_aid"),
    ADVERTISING_TRACKING_ENABLED("_ate"),
    ADWORDS_CLICK_REFERRER("_awcr"),
    ADWORDS_CONVERSION("_awct"),
    AJAX_SUBMIT_LISTENER("_ajl"),
    APP_ID("_ai"),
    APP_NAME("_an"),
    APP_VERSION("_av"),
    ARBITRARY_HTML("_html"),
    ARBITRARY_JAVASCRIPT("_jsm"),
    ARBITRARY_PIXEL("_img"),
    BIZO_INSIGHT("_bzi"),
    CLICK_LISTENER("_cl"),
    CLICK_TALE_STANDARD("_cts"),
    COMSCORE_MEASUREMENT("_csm"),
    CONFIGURATION_VALUE("_cv"),
    CONSTANT("_c"),
    CONTAINER_VERSION("_ctv"),
    CONTAINS("_cn"),
    COOKIE("_k"),
    CRITEO("_crt"),
    CUSTOM_VAR("_v"),
    DATA_LAYER_WRITE("_dlw"),
    DEBUG_MODE("_dbg"),
    DEVICE_ID("_did"),
    DEVICE_NAME("_dn"),
    DEVICE_TYPE("_dt"),
    DOM_ELEMENT("_d"),
    ELEMENT_TEXT("_et"),
    ENCODE("_enc"),
    ENDS_WITH("_ew"),
    EQUALS("_eq"),
    EVENT("_e"),
    FLOODLIGHT_COUNTER("_flc"),
    FLOODLIGHT_SALES("_fls"),
    FORM_SUBMIT_LISTENER("_fsl"),
    FUNCTION_CALL("_func"),
    GOOGLE_AFFILIATE_NETWORK("_gan"),
    GOOGLE_ANALYTICS("_ga"),
    GOOGLE_TAG_MANAGER("_gtm"),
    GREATER_EQUALS("_ge"),
    GREATER_THAN("_gt"),
    GTM_VERSION("_gtmv"),
    HASH("_hsh"),
    HISTORY_LISTENER("_hl"),
    INSTALL_REFERRER("_ir"),
    JOINER("_jn"),
    JS_ERROR_LISTENER("_jel"),
    JS_GLOBAL("_j"),
    LANGUAGE("_l"),
    LESS_EQUALS("_le"),
    LESS_THAN("_lt"),
    LINK_CLICK_LISTENER("_lcl"),
    MARIN_SOFTWARE("_ms"),
    MEDIA6DEGREES_UNIVERSAL_PIXEL("_m6d"),
    MEDIAPLEX_MCT("_mpm"),
    MEDIAPLEX_ROI("_mpr"),
    MOBILE_ADWORDS_UNIQUE_ID("_awid"),
    OS_VERSION("_ov"),
    PLATFORM("_p"),
    QUANTCAST_MEASUREMENT("_qcm"),
    RANDOM("_r"),
    REFERRER("_f"),
    REGEX("_re"),
    REGEX_GROUP("_reg"),
    RESOLUTION("_rs"),
    RUNTIME_VERSION("_rv"),
    SDK_VERSION("_sv"),
    SIMPLE_MAP("_smm"),
    SMART_PIXEL("_sp"),
    STARTS_WITH("_sw"),
    TARGUS_ADVISOR("_ta"),
    TIME("_t"),
    TIMER_LISTENER("_tl"),
    TRUSTED_STORES("_ts"),
    TURN_CONVERSION("_tc"),
    TURN_DATA_COLLECTION("_tdc"),
    UNIVERSAL_ANALYTICS("_ua"),
    URL("_u"),
    VISUAL_DNA_CONVERSION("_vdc");

    private final String name;

    static {
        FunctionType[] var0 = new FunctionType[]{ADVERTISER_ID, ADVERTISING_TRACKING_ENABLED, APP_ID, APP_NAME, APP_VERSION, ARBITRARY_JAVASCRIPT, CONSTANT, COOKIE, CUSTOM_VAR, CONTAINER_VERSION, DEBUG_MODE, DEVICE_NAME, DEVICE_TYPE, DOM_ELEMENT, ELEMENT_TEXT, EVENT, FUNCTION_CALL, JS_GLOBAL, LANGUAGE, OS_VERSION, PLATFORM, RANDOM, REFERRER, RESOLUTION, RUNTIME_VERSION, SDK_VERSION, SIMPLE_MAP, TIME, URL, ADWORDS_CLICK_REFERRER, DEVICE_ID, ENCODE, GTM_VERSION, HASH, INSTALL_REFERRER, JOINER, MOBILE_ADWORDS_UNIQUE_ID, REGEX_GROUP, DATA_LAYER_WRITE, REGEX, STARTS_WITH, ENDS_WITH, CONTAINS, EQUALS, LESS_THAN, LESS_EQUALS, GREATER_THAN, GREATER_EQUALS, ARBITRARY_PIXEL, ARBITRARY_HTML, GOOGLE_TAG_MANAGER, GOOGLE_ANALYTICS, ADWORDS_CONVERSION, SMART_PIXEL, FLOODLIGHT_COUNTER, FLOODLIGHT_SALES, BIZO_INSIGHT, QUANTCAST_MEASUREMENT, TARGUS_ADVISOR, MEDIAPLEX_ROI, COMSCORE_MEASUREMENT, TURN_CONVERSION, TURN_DATA_COLLECTION, MEDIA6DEGREES_UNIVERSAL_PIXEL, UNIVERSAL_ANALYTICS, MEDIAPLEX_MCT, VISUAL_DNA_CONVERSION, GOOGLE_AFFILIATE_NETWORK, MARIN_SOFTWARE, ADROLL_SMART_PIXEL, CONFIGURATION_VALUE, CRITEO, TRUSTED_STORES, CLICK_TALE_STANDARD, LINK_CLICK_LISTENER, FORM_SUBMIT_LISTENER, TIMER_LISTENER, CLICK_LISTENER, JS_ERROR_LISTENER, HISTORY_LISTENER, AJAX_SUBMIT_LISTENER};
    }

    private FunctionType(String var3) {
        this.name = var3;
    }

    public String toString() {
        return this.name;
    }
}
